2017-02-22 10:09:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:13:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:21:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:30:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:31:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:33:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:36:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 10:54:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 11:12:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 11:15:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:12:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:15:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:16:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:21:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:21:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:27:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:28:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:38:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 12:39:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 13:17:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 13:27:42 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariRDBMSDataSource.getDataSource(HikariRDBMSDataSource.java:56)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariDataSourceReader.createDataSource(HikariDataSourceReader.java:74)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:64)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildCarbonDataSource(DataSourceBuilder.java:44)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSource(DataSourceManager.java:163)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:137)
	at org.wso2.carbon.datasource.core.internal.DataSourceListenerComponent.onAllRequiredCapabilitiesAvailable(DataSourceListenerComponent.java:98)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$5(StartupComponentManager.java:237)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:225)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:186)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 40 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 35 more
2017-02-22 13:31:36 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariRDBMSDataSource.getDataSource(HikariRDBMSDataSource.java:56)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariDataSourceReader.createDataSource(HikariDataSourceReader.java:74)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:64)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildCarbonDataSource(DataSourceBuilder.java:44)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSource(DataSourceManager.java:163)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:137)
	at org.wso2.carbon.datasource.core.internal.DataSourceListenerComponent.onAllRequiredCapabilitiesAvailable(DataSourceListenerComponent.java:98)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$5(StartupComponentManager.java:237)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:225)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:186)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 40 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 35 more
2017-02-22 13:34:58 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariRDBMSDataSource.getDataSource(HikariRDBMSDataSource.java:56)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariDataSourceReader.createDataSource(HikariDataSourceReader.java:74)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:64)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildCarbonDataSource(DataSourceBuilder.java:44)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSource(DataSourceManager.java:163)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:137)
	at org.wso2.carbon.datasource.core.internal.DataSourceListenerComponent.onAllRequiredCapabilitiesAvailable(DataSourceListenerComponent.java:98)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$5(StartupComponentManager.java:237)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:225)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:186)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 40 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/wso2/repo/carbon-identity-mgt/tests/osgi-tests/database/WSO2LIFECYCLE_DB.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 35 more
2017-02-22 13:39:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 13:46:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 13:49:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 14:05:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-22 14:09:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-24 17:13:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-24 17:14:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-24 17:23:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-24 17:50:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-27 09:49:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
2017-02-27 09:54:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LC_DEFINITIONS" not found; SQL statement:
select 1 from LC_DEFINITIONS [42102-191]
